### ISSUE TITLE
[Bug] Adding builder-vite to main config file launches actual app instead of playground

### ISSUE THREAD

**Issue by SamuelPoulin** [storybookjs/builder-vite#446] opened 2022-07-15 19:13 UTC
### What version of `vite` are you using?

3.0.0

### System info and storybook versions

System:
  OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Binaries:
  Node: 16.15.1 - /usr/bin/node
  Yarn: 1.22.18 - /usr/bin/yarn
  npm: 8.11.0 - /usr/bin/npm

### Describe the Bug

Hello, I have created a minimal repo here to reproduce the bug. Here is how to do it:

Steps:
1- Clone the repo
2- Execute `yarn` inside the repo
3- Execute `yarn storybook` inside the repo
4- Visit http://localhost:6006/ and see that the storybook playground is working just fine
5- Stop `yarn storybook`
6- Go to `.storybook/main.ts`
7- Uncomment lines 10-12 to enable builder-vite
8- Relaunch `yarn storybook`
9- The page hosted at localhost:6006 now displays the actual app instead of the playground

### Link to Minimal Reproducible Example

: https://github.com/SamuelPoulin/vite-react-typescript-storybook-minimal

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by TPOborne** [comment] 2022-07-16 17:43
Can confirm I'm also seeing this issue. Running `yarn storybook --no-manager-cache` seems to fix it temporarily. If I run `yarn storybook` the first time after the `--no-manage-cache` run then it works. Any subsequent run of `yarn storybook` however comes across this issue again.

**Comment by ldegen** [comment] 2022-07-17 08:36
Hi, I think I am experiencing the same problem here. Initially, I thought this might be related to me using yarn (canary, I think), but the same thing happens with plain old npm.

**Comment by EdimarioJr** [comment] 2022-07-19 01:25
Can confirm, I'm also seeing this issue.

**Comment by IanVS** [comment] 2022-07-21 02:05
Thanks for providing a reproduction, @SamuelPoulin, that was super helpful since I don't experience this in my own app or in the examples in this repo (I don't know why).  I've found the reason this is happening, and we should have a new version with a fix out soon.

**Comment by IanVS** [comment] 2022-07-25 17:40
Thanks everyone.  A fix for this has been released in `@storybook/builder-vite` [0.2.1](https://github.com/storybookjs/builder-vite/discussions/462).

**Comment by SamuelPoulin** [comment] 2022-07-26 18:11
I bumped the version of builder-vite in https://github.com/SamuelPoulin/vite-react-typescript-storybook-minimal and unfortunately I'm still getting this problem when uncommenting the builder...

**Comment by IanVS** [comment] 2022-07-26 18:26
Thanks, I screwed up the config it seems.  For now, you can work around this by using `config.appType = 'custom'` in `viteFinal`.

**Closed** 2022-07-26 20:25 UTC
Labels: bug
