### ISSUE TITLE
[Bug] @storybook/addon-backgrounds stopped working in storybook-builder-vite v0.1.23

### ISSUE THREAD

**Issue by Nagell** [storybookjs/builder-vite#325] opened 2022-04-08 10:14 UTC
### Describe the bug

After updating "storybook-builder-vite" from "0.1.22" to "0.1.23" i realized that "@storybook/addon-backgrounds" which is a part of "@storybook/addon-essentials" stopped working correctly in Build. 

It is still working as it should while just running under vite though.

### Steps to reproduce the behavior

1. Create a new Project with "@storybook/addon-essentials": 6.4.20 and "storybook-builder-vite": "0.1.23"
2. Configure preview.js like this:
```js
export const parameters = {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
        matchers: {
            color: /(background|color)$/i,
            date: /Date$/,
        },
        expanded: true
    },

    backgrounds: {
        default: 'light',
        values: [
            {
                name: 'white',
                value: "#FFFFFF"
            },
            {
                name: 'blue',
                value: "#0376BB"
            },
            {
                name: 'light',
                value: "#F8F8F8"
            },
            {
                name: 'dark',
                value: "#090716"
            },
        ]
    }
}
```

3. Build Storybook and run it somewhere (ex. Live Server in VSC)
4. Try to change Background Color in a Story

### Expected behavior

Background color should change.

### Screenshots and/or logs

![Bildschirmfoto 2022-04-08 um 12 06 20](https://user-images.githubusercontent.com/4633237/162414860-92409ee9-c19a-4e86-b8b8-a1c932279c5d.png)

### Environment

 - OS: macOS 12.2.1 
 - Node.js version: 17.8.0
 - NPM version: 8.5.5

**Comment by IanVS** [comment] 2022-04-08 12:09
Thanks for the report.  Just curious, does it work correctly if you enable `storyStoreV7`?

**Comment by IanVS** [comment] 2022-04-08 13:38
@Nagell I've tried, but I've been unable to reproduce this.  Do you mind creating a repo that demonstrates the issue that I can take a look at?

**Comment by joshwooding** [comment] 2022-05-15 00:29
Closing this for now since now reproduction has been provided.

**Closed by joshwooding** 2022-05-15 00:29 UTC
Labels: bug, needs reproduction
