### ISSUE TITLE
[Bug] Rollup plugin working locally but not on static build

### ISSUE THREAD

**Issue by troyvassalotti** [storybookjs/builder-vite#345] opened 2022-04-21 20:04 UTC
### Describe the bug

We use Storybook with Lit. In our Lit components, we `import` SCSS files.

```ts
import { html, LitElement } from "lit";
import style from "./quote-block.scss";

@customElement("component-name")
export class ComponentName extends LitElement {
  static get styles() {
    return [ style ];
  }
}
...
```

To import SCSS and not need to wrap all our imported styles in the `unsafeCSS()` function from Lit, we use a plugin in our Vite config - [`rollup-plugin-postcss-lit`](https://github.com/umbopepato/rollup-plugin-postcss-lit). I've also added this plugin to `main.js` in Storybook.

![image](https://user-images.githubusercontent.com/45142012/164543291-b8fd21b3-95f2-44a9-a37a-f111e71ab66f.png)

Components render as expected with `start-storybook`, but the components do not render when using `build-storybook` and viewing the resulting static pages. We are met with console errors:

![image](https://user-images.githubusercontent.com/45142012/164542796-1bfc8a97-5e68-42a8-8fd2-352f2efea5b9.png)

### Environment

 - Node.js version: [e.g. v14.19.1]
 - NPM version: [e.g. 6.14.16]

### Additional context

Because the plugin works with a dev server, and after not finding an answer in other repos, I am hoping someone here can provide some insight into why this would be happening, thank you.

**Comment by IanVS** [comment] 2022-04-21 20:54
Thanks for the report.  I haven't worked with lit before, so I may not be a ton of help here, but I have a few questions.  Have you been using storybook with lit previously, and it started to break when you changed to the vite builder?  Does the rest of your app work just fine when building for production (without storybook)?  Are you using https://www.npmjs.com/package/@storybook/lit?  I don't see a `framework` specified in your `main.js` file.

We don't currently have an example project in this repo using lit.  It would be super useful if you were able to submit a PR to add one, ideally one which reproduces the problem you're having.  Then we'll be able to explore a bit and see if we can figure out what's going on.

**Comment by IanVS** [comment] 2022-04-21 21:01
Have you tried adding `?inline` to your imports? https://github.com/umbopepato/rollup-plugin-postcss-lit/issues/40#issuecomment-1063309922

**Comment by troyvassalotti** [comment] 2022-04-22 14:20
Hey @IanVS! Thanks for the quick response. I can clarify a bit on this:

1. We went from webpack to vite - both with Lit - and it was working prior because we used [lit-scss-loader](https://www.npmjs.com/package/lit-scss-loader). The rollup plugin we want to use has a similar goal.
2. Everything else with our build works as intended. The `start-storybook` preview shows our expected results; it is only the `build-storybook` result that doesn't seem to take the plugin into account.
3. Neither adding `framework: "@storybook/web-components"` or `?inline` address the issue.

I got a _very simple_ local branch example that gives the same result (sans the console error it seems, but the lack of styles does continue) and I would be happy to submit a PR for it in a few.

**Comment by IanVS** [comment] 2022-04-22 22:19
Thanks @troyvassalotti!  I left a [comment](https://github.com/storybookjs/builder-vite/pull/350#discussion_r856598705) in the PR, but for anyone following along here, this is an issue with an incompatibility between the default `include` picomatch of the plugin, vs the filenames that vite generates (which can include a query param).  I'm going to close this issue since there's a workaround, and the main issue is not in this package, but I'm glad you stopped by, and I'm excited to have a `lit` example in our repo.

**Closed by IanVS** 2022-04-22 22:19 UTC
Labels: bug
