### ISSUE TITLE
storyName override in StoryObj / ComponentStoryObj doesn't work with storyStoreV7

### ISSUE THREAD

**Issue by Guria** [storybookjs/builder-vite#253] opened 2022-02-22 07:26 UTC
**Steps to reproduce:**
* clone repo at main branch (v0.1.17 at the moment of writing this issue)
* open packages/example-react-ts/stories/Button.stories.tsx
* edit Primary ComponentStoryObj declaration to have storyName property:
```
export const Primary: ComponentStoryObj<typeof Button> = {
  args: {
    primary: true,
    label: 'Button',
  },
  storyName: 'Override'
};
```
* run `yarn example:react-ts`
* open storybook in browser and check how stories for Button named in sidebar

**Actual:**
![image](https://user-images.githubusercontent.com/36270/155081625-d56df84a-2586-4b17-ab95-9b9331753471.png)

Story still named using ComponentStoryObj export name.

**Expected:**

Story should be named as defined in `storyName` property of ComponentStoryObj.

**Comments:**
Reproducible only with:
```
core: {
  builder: 'storybook-builder-vite',
}
```
Works correctly with default builder of storybook.

**Comment by Guria** [comment] 2022-02-22 11:32
I've found that `name` property is working in ComponentStoryObj. Not sure if it is intended to storyName to work

**Comment by IanVS** [comment] 2022-02-22 14:23
Strange, I use `storyName` extensively in my own project and have not had any trouble with it, including with the latest 0.1.17 version.  Any chance you could make a reproduction for us to investigate?

**Comment by IanVS** [comment] 2022-02-22 14:45
@Guria we use CSF3 objects.  I also just tested in the `example-react` example project in this repo, and it seems to work there as well...

<img width="469" alt="image" src="https://user-images.githubusercontent.com/4616705/155155659-477b6603-731c-4f4e-89df-4d463eb87f10.png">

**Comment by Guria** [comment] 2022-02-22 18:21
@IanVS 
reproduction is as simple as defined in my initial message. I've checked example-react + storyName is working. examle-react-ts + storyName doesn't.
![image](https://user-images.githubusercontent.com/36270/155194706-28f091b2-a84f-4526-aa41-10aeefd5e831.png)

**Comment by Guria** [comment] 2022-02-22 18:23
I have no proves right now, but i believe that I've checked plain storybook with typescript and default builder and storyName override was working there. I will try to double check it.

**Comment by IanVS** [comment] 2022-02-22 18:28
Ah, thanks for that detail about react-ts.  It seems this is a bug that happens when `storyStoreV7` is enabled.  👍

**Comment by Guria** [comment] 2022-02-22 18:42
confirm that it affects only `storyStoreV7` also cra+ts+sb/webpack5 is also affected when enabling `storyStoreV7`.
Closing issue here. Could you suggest which upstream package fits better for this issue?

**Comment by IanVS** [comment] 2022-02-22 18:48
I think it's a bug here, actually.  Thanks for finding it!

**Comment by IanVS** [comment] 2022-02-22 18:49
Oh, I misread, it happens to webpack too?  Hmmmmmm

**Comment by Guria** [comment] 2022-02-22 18:51
Yes, I think the source of issue is somewhere around: 
https://github.com/storybookjs/storybook/blob/main/lib/store/src/normalizeStory.ts#L47-L51

**Comment by IanVS** [comment] 2022-02-22 18:52
I don't see any existing issue in the main storybook repo.  I think it's worth opening there, but let's keep this open too for now at least.

**Comment by Guria** [comment] 2022-02-22 18:54
I will file an issue there and provide a link

**Comment by joshwooding** [comment] 2022-06-12 11:13
Hi @Guria, there has been an update on this. You might want to read https://github.com/storybookjs/storybook/issues/17548 but it's intended that storyName doesn't work when using CSF3. "name" should be used instead but there is a bug with the CSF3 types that will be investigated. Thank you for your patience.

**Closed by joshwooding** 2022-06-12 11:13 UTC
Labels: upstream
