### ISSUE TITLE
[Bug] Stories globs not matching on fresh install

### ISSUE THREAD

**Issue by viniciusflv** [storybookjs/builder-vite#507] opened 2022-10-04 14:01 UTC
### What version of `vite` are you using?

3.1.4

### System info and storybook versions

System:
  OS: windows 10
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz @ 2.80 GHz
Binaries:
  Node: 16.14.2
  Yarn: 1.22.18
  npm: 8.5.5
Browsers:
  chrome: 105.0.5195.128
npmPackages:
  "@storybook/addon-actions": "^6.5.12",
  "@storybook/addon-essentials": "^6.5.12",
  "@storybook/addon-interactions": "^6.5.12",
  "@storybook/addon-links": "^6.5.12",
  "@storybook/builder-vite": "^0.2.3",
  "@storybook/react": "^6.5.12",
  "@storybook/testing-library": "^0.0.13",

### Describe the Bug

Fresh install using `npm create vite@latest` and `npx sb@latest init` it's not finding stories.

```
Couldn't find any stories in your Storybook.
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
```

### Link to Minimal Reproducible Example

https://github.com/viniciusflv/storybook-glob-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment] 2022-10-04 14:14
Thanks for the reproduction.  It's working fine on my mac, but I see you're using windows.  Maybe someone with a windows machine can help to verify and troubleshoot?  @joshwooding do you have a windows box you could try this on?

**Comment by joshwooding** [comment] 2022-10-04 21:38
This works for me too

**Comment by IanVS** [comment] 2022-10-04 21:49
I'll leave this open for a while in case anyone else runs into it, but it seems like maybe it's something going on with your local machine, @viniciusflv.

**Comment by viniciusflv** [comment] 2022-10-05 13:26
Thanks @IanVS and @joshwooding for the quick response.

It's my bad for not trying with a different OS. Unfortunately I won´t be able to provide a sandbox, but since will remain open I'll give more context.

The machine is not mine so I can only install stuff through scoop. Webpack builder works fine, so no worries.
It was working fine until really recent, probably vite related, I had received the following error:

```
Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/preview-entry.js       
  1  |  import * as preview from ...
```

That was what motivated me to try a fresh installation.

PS: I can reproduce it on my machine, if I comment the storyStoreV7.

```
// features: {
//   storyStoreV7: true,
// },
```

**Comment by joshwooding** [comment] 2022-10-08 12:40
@viniciusflv I tried to reproduce it again commenting out storyStoreV7 but it still works fine for me...

Not sure what's causing the inconsistency here 🤔

**Comment by gabrielcarloto** [comment] 2022-10-12 00:25
I'm getting the same error. Tried with npm (8.15.0), pnpm (7.13.4) and yarn (1.22.19) on win 11, but nothing works. In the browser (firefox) console, there is also this error: `Unable to load story '*'`.

My `vite` version is 3.1.7

When I comment the `storyStoreV7`, I get an infinite loading screen and this error:

```
21:20:18 [vite] Internal server error: Failed to resolve import "E:UsuáriosDocumentosPrincipaisProjetosProgramaçãoCursosRocket SeatIgnite Lab 4lab-ds.storybookpreview.cjs" from "..\..\..\..\..\..\..\..\..\virtual:\@storybook\builder-vite\preview-entry.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/preview-entry.js
  1  |  import * as preview from 'E:\Usuários\Documentos\Principais\Projetos\Programação\Cursos\Rocket Seat\Ignite Lab 4\lab-ds\.storybook\preview.cjs';
     |                            ^
  2  |    export default preview;
```

**Comment by IanVS** [comment] 2022-10-12 11:31
@gabrielcarloto can you share the `stories` config from your `main.js`?  I'm thinking maybe you used backslashes in your glob, instead of forward slashes.

**Comment by gabrielcarloto** [comment] 2022-10-12 12:16
@IanVS here it is:

```js
stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)']
```

**Comment by viniciusflv** [comment] 2022-10-14 20:30
It is working now. As suspected it's probably something with my machine config.

Yesterday I had to reinstall everything from scratch, for a unrelated issue, so I think maybe it was some sort of global cache that
`npm cache clean -f` wasn't able to clear.

```
$ node -v
v16.18.0

$ yarn -v
1.22.19

$ npm -v
8.19.2
```

Thank you all for the incredible work and for the quick feedback.

**Comment by joshwooding** [comment] 2022-10-15 15:19
Thanks for the update @viniciusflv. Closing this issue now

**Closed by joshwooding** 2022-10-15 15:19 UTC
Labels: bug
