### ISSUE TITLE
[Bug] Typsecript types aren't recognized and not showing on storybook docs.

### ISSUE THREAD

**Issue by AbdallahAbis** [storybookjs/builder-vite#369] opened 2022-05-06 00:18 UTC
### What version of `vite` are you using?

^2.9.7

### System info and storybook versions

```
  System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.23.0-20220130.1630 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 99.0.1
    Safari: 15.4
```

### Describe the Bug

using the default webpack builder:

![Screen Shot 2022-05-06 at 00 08 14](https://user-images.githubusercontent.com/59185227/167046170-47c963d8-49ce-4f03-b709-bb2304bc892e.png)

using `@storybook/builder-vite`
![Screen Shot 2022-05-06 at 00 09 51](https://user-images.githubusercontent.com/59185227/167046298-807efa4a-1008-4fe3-b47e-6383a9297cfa.png)

types variable:
```export type types = React.ComponentProps<typeof StyledButton>```

`StyledButton` is a Stitches styled button:
```
const StyledButton = styled('button', {
  variants: {
    variant: {
      primary: {},
      secondary: {},
      ghost: {},
    },
    size: {
      sm: {},
      md: {},
      lg: {},
    },
    block: {
      true: {},
    },
  },
})
```

Please let me know if I'm doing anything wrong?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment] 2022-05-06 02:40
Hi, without a reproduction, this is going to be difficult to troubleshoot.  I'm not familiar with stitches, which is why it would be very helpful if you can create a new small repo with a simple component, which I can dig into.

**Comment by joshwooding** [comment] 2022-07-14 10:04
Closing due to staleness. Will re-open if we get a reproduction. Thanks for the report.

**Closed by joshwooding** 2022-07-14 10:04 UTC
Labels: bug, needs reproduction
