### ISSUE TITLE
Can't use SvelteKit $app stores in Stories

### ISSUE THREAD

**Issue by kyleshepherd** [storybookjs/builder-vite#321] opened 2022-04-07 12:01 UTC
I'm trying to get a basic story working using SvelteKit + Storybook using the Vite builder. This story uses the  `page` store from`$app/stores` which is imported into the `Nav.svelte` file as below:
```
import { page } from "$app/stores";
```

In my `.storybook/main.js` file, I have this config including the alias for the `$app`
```
const preprocess = require("svelte-preprocess");
const autoprefixer = require("autoprefixer");
const path = require("path");
const { mergeConfig } = require("vite");

module.exports = {
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-svelte-csf",
  ],
  framework: "@storybook/svelte",
  svelteOptions: {
    preprocess: preprocess({
      sourceMap: true,
      scss: {
        includePaths: ["src"],
        prependData: `@import 'src/styles/variables.scss';`,
      },
      postcss: {
        plugins: [autoprefixer()],
      },
      aliases: [["ts", "typescript"]],
    }),
  },
  core: {
    builder: "@storybook/builder-vite",
  },
  async viteFinal(config, { configType }) {
    config.resolve.alias = {
      $app: path.resolve("./.svelte-kit/runtime/app"),
    };
    console.log(config);
    return config;
  },
};

```

but when I try to view the Nav story, I get the below error
```
Cannot read properties of undefined (reading 'page')
TypeError: Cannot read properties of undefined (reading 'page')
    at getStores (http://localhost:6006/.svelte-kit/runtime/app/stores.js:23:22)
    at Object.subscribe (http://localhost:6006/.svelte-kit/runtime/app/stores.js:45:17)
    at subscribe (http://localhost:6006/node_modules/.vite-storybook/chunk-R7OMEHAZ.js?v=3466fb57:61:23)
    at component_subscribe (http://localhost:6006/node_modules/.vite-storybook/chunk-R7OMEHAZ.js?v=3466fb57:70:32)
    at instance (http://localhost:6006/src/components/Nav/Nav.svelte:121:2)
    at init (http://localhost:6006/node_modules/.vite-storybook/chunk-R7OMEHAZ.js?v=3466fb57:1686:23)
    at new Nav (http://localhost:6006/src/components/Nav/Nav.svelte:137:3)
    at createProxiedComponent (http://localhost:6006/node_modules/svelte-hmr/runtime/svelte-hooks.js:266:9)
    at new ProxyComponent (http://localhost:6006/node_modules/svelte-hmr/runtime/proxy.js:239:20)
    at new Proxy<Nav> (http://localhost:6006/node_modules/svelte-hmr/runtime/proxy.js:346:11)
```

Has anyone been able to successfully set an alias to the `$app/stores`?

**Comment by kyleshepherd** [comment] 2022-04-07 13:15
Here you go https://github.com/kyleshepherd/svelte-kit-storybook, any issues lemme know!

**Comment by IanVS** [comment] 2022-04-07 13:32
Thanks @kyleshepherd.  I'm trying it out, but when I run `npm run storybook` after installing deps, I'm seeing this in the browser console:

```
:6006/.svelte-kit/runtime/app/stores:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```

Am I missing a step?

**Comment by IanVS** [comment] 2022-04-07 13:32
Oh, it seems I need to also be running `npm run dev`, I guess.

**Comment by IanVS** [comment] 2022-04-07 13:54
So, it seems the import resolution itself is working fine, because if I remove the uses of `$page` in the component, and just log out the import, it resolves correctly.  However, and this is where my svelte (and especially svelteKit) knowledge fails me, The `$page` is failing.  I'm not sure exactly what that's doing, but it seems to be trying to take the `Readable` `page`, and I guess read from it, and that part is failing.  Does that give you anything to go off of?  

Another thing to try, does this work correctly when using webpack?  I wasn't able to with poking at it for a few minutes, but that would be interesting to narrow down where the error is happening.

One more small tip, you can use `svelteOptions: import("../svelte.config.js").preprocess,`, rather than re-creating the config in the `main.js`.

**Comment by kyleshepherd** [comment] 2022-04-07 13:56
I did try it with Webpack but was getting a similar error. 

I'll try and do some more digging now knowing that the alias is working itself and see if I can figure anything out. Thank you for looking into it!

**Comment by benbender** [comment] 2022-04-18 15:22
The problem is neither storybook nor vite/webpack directly. Sveltekit is simply prefilling some vars per request and that step is missing on those simple aliasing-setups. One solution can be adapted from this: https://github.com/nickbreaton/vitest-svelte-kit/blob/master/packages/vitest-svelte-kit/src/plugins/kit-module-emulator.ts

**Comment by IanVS** [comment] 2022-04-26 14:20
I'm going to close this out since it doesn't sound like a builder-vite bug, but please report back @kyleshepherd if you think it is, or if you find a good solution that you think might be useful to others.

**Closed by IanVS** 2022-04-26 14:20 UTC

**Comment by hugotox** [comment] 2023-12-29 01:02
> The problem is neither storybook nor vite/webpack directly. Sveltekit is simply prefilling some vars per request and that step is missing on those simple aliasing-setups. One solution can be adapted from this: https://github.com/nickbreaton/vitest-svelte-kit/blob/master/packages/vitest-svelte-kit/src/plugins/kit-module-emulator.ts

Hey @benbender, thanks for this. Do you happen to know any way to implement that? I can't find how to connect the dots between sveltekit, storybook and vite

**Comment by shilman** [comment] 2023-12-29 15:37
Cc @JReinhold

**Comment by JReinhold** [comment] 2023-12-29 16:58
@hugotox have you checked out https://github.com/storybookjs/storybook/blob/next/code%2Fframeworks%2Fsveltekit%2FREADME.md ?

Note that it requires Storybook 7.0, and we even recently made more improvements to the SvelteKit integration so I'd suggest you upgrade to the latest Storybook version 7.6.6 before moving forward. `npx storybook@latest upgrade`

Do you need anything else not covered in the current functionality?

**Comment by hugotox** [comment] 2023-12-29 17:09
@JReinhold yes I have! The upgrade to storybook 7.6.6 worked, but it broke my main.js file

```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: /Users/hugo/Projects/stickmonkey/node_modules/@storybook/addon-svelte-csf/dist/index.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

/Users/hugo/Projects/stickmonkey/node_modules/@storybook/addon-svelte-csf/dist/components/Meta.svelte:1
<script>
^

SyntaxError: Unexpected token '<'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader (/Users/hugo/Projects/stickmonkey/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/hugo/Projects/stickmonkey/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at loadPreset (/Users/hugo/Projects/stickmonkey/node_modules/@storybook/core-common/dist/index.js:15:82)
```

If I revert the main.js back, storybook works again.

For reference, the main.js was changed to

```js
import { dirname, join } from "path";
/** @type { import('@storybook/svelte-vite').StorybookConfig } */
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx|svelte)'],
  addons: [
    getAbsolutePath("@storybook/addon-svelte-csf"),
    getAbsolutePath("@storybook/addon-links"),
    getAbsolutePath("@storybook/addon-essentials"),
    getAbsolutePath("@storybook/addon-interactions"),
    getAbsolutePath("@storybook/addon-styling"),
    getAbsolutePath("@storybook/addon-storysource"),
  ],
  framework: {
    name: getAbsolutePath("@storybook/sveltekit"),
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
}
export default config

function getAbsolutePath(value) {
  return dirname(require.resolve(join(value, "package.json")));
}
```

And to make it work, I reverted it back to:

```js
/** @type { import('@storybook/svelte-vite').StorybookConfig } */
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx|svelte)'],
  addons: [
    '@storybook/addon-svelte-csf',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-styling',
    '@storybook/addon-storysource',
  ],
  framework: {
    name: '@storybook/sveltekit',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
}
export default config
```

---

**Update**
I'm able to mock the page store in svelte format by adding the parameters key to the meta object. E.g.

```js
 export const meta = {
    title: 'My Component',
    component: MyComponent,
    parameters: {
      sveltekit_experimental: {
        stores: {
          page: {
            url: '/',
          },
        },
      },
    },
  }
```

**Comment by JReinhold** [comment] 2023-12-29 19:23
@hugotox your issue sounds related to https://github.com/storybookjs/addon-svelte-csf/issues/160#issue-2008996585 . Resolving dependencies in monorepos is hard, thanks for reporting the workaround - I don't think there's any wrong with your solution.

Sounds like your issue is resolved then. FYI if you need to, you should also be able to mock the stores on a per-story basis by setting the parameters on the Story component directly.

**Comment by tomolenet** [comment] 2024-01-24 11:12
Yes, it seems to work. I tested it [here](https://github.com/tomolenet/addon-svelte-csf-160).

It seems to work now that you just have to remove `getAbsolutePath`. The `workspace` can stay.
