### ISSUE TITLE
Unable to build docs in mdx format

### ISSUE THREAD

**Issue by wanbinkimoon** [storybookjs/builder-vite#221] opened 2022-01-30 23:22 UTC
I'm using `storybook-builder-vite@^0.1.13` which include `vite-plugin-mdx@3.5.10`
but a simple file like this 
```mdx
import { Canvas, Meta, Story } from '@storybook/addon-docs';
import { Button, Space } from '../../index';

<Meta title="MDX/Button" component={Button} />

# Button

<Canvas>
  <Story name="primary button">
    <div>
      <Button size="large" variant="primary" onClick={() => {}}>
        Click me
      </Button>
    </div>
  </Story>
</Canvas>
);

```

throw a parsing error 

```log
 00:18:46 [vite] Internal server error: Unexpected token (10:0)
[1]   Plugin: vite-plugin-mdx
[1]   File: /src/components/Button/Button-doc.stories.mdx
[1]   7  |  
[1]   8  |  <Canvas>
[1]   9  |    <Story name="primary button">
```

**Comment by wanbinkimoon** [comment] 2022-01-30 23:37
UPDATE: Apparently the `Canvas` element **must be** always inside a `Story` component


This seems to be incoherent with the storybook mdx documentation that in the **[Basic Example](https://storybook.js.org/docs/react/writing-docs/mdx#basic-example
)** linked clearly shows the opposite pattern.

```jsx
<Canvas>
  <Story 
    name="Unchecked"
    args={{ 
      label: 'Unchecked',
    }}>
    {Template.bind({})}
   </Story>
</Canvas>
```

**Comment by joshwooding** [comment] 2022-01-31 16:56
Could you provide a minimum reproducible example? This example works fine for me: https://github.com/eirslett/storybook-builder-vite/blob/main/packages/example-react/stories/mdx-in-stories/Example.docs.mdx

**Comment by joshwooding** [comment] 2022-05-15 00:41
Closing this for now since now reproduction has been provided.

**Closed by joshwooding** 2022-05-15 00:41 UTC
Labels: awaiting clarification
