### ISSUE TITLE
[Bug] Not works with pnpm

### ISSUE THREAD

**Issue by boeto** [storybookjs/builder-vite#455] opened 2022-07-22 05:26 UTC
### What version of `vite` are you using?

^3.0.2

### System info and storybook versions

System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-vite: ^0.2.0 => 0.2.0 
    @storybook/web-components: ^6.5.9 => 6.5.9 

### Describe the Bug

Steps:
1. `git clone https://github.com/boeto/minimal-reproducible-builder-vite.git`
2. `cd minimal-reproducible-builder-vite`
3. `pnpm i`
4. `pnpm run storybook`
5. get the errors:
```
[plugin:vite:import-analysis] Failed to resolve import "@storybook/preview-web" from "../../../../../../../../virtual:/@storybook/builder-vite/vite-app.js". Does the file exist?
/virtual:/@storybook/builder-vite/vite-app.js:1:45
1  |  import { composeConfigs, PreviewWeb } from '@storybook/preview-web';
```

---

Additional information:
- works in one of the following environments
  1. works wiht `npm i && npm run run storybook`
  2. works wiht use coreBuilder: `webpack5`

### Link to Minimal Reproducible Example

https://github.com/boeto/minimal-reproducible-builder-vite

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment] 2022-07-26 13:23
Hi, thanks for the reproduction.  This is a duplicate of an existing issue, https://github.com/storybookjs/builder-vite/issues/55, so you can take a look there for some hints of how to deal with it for now, until a better solution is found.

**Closed by IanVS** 2022-07-26 13:23 UTC
Labels: bug
