### ISSUE TITLE
[Bug] MDXv2 support

### ISSUE THREAD

**Issue by shilman** [storybookjs/builder-vite#375] opened 2022-05-09 06:22 UTC
### What version of `vite` are you using?

2.9.8

### System info and storybook versions

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.0 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 8.1.0 - ~/n/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 95.0.2
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.0-beta.7 => 6.5.0-beta.7
    @storybook/addon-essentials: ^6.5.0-beta.7 => 6.5.0-beta.7
    @storybook/addon-interactions: ^6.5.0-beta.7 => 6.5.0-beta.7
    @storybook/addon-links: ^6.5.0-beta.7 => 6.5.0-beta.7
    @storybook/builder-vite: ^0.1.33 => 0.1.33
    @storybook/mdx2-csf: ^0.0.3 => 0.0.3
    @storybook/react: ^6.5.0-beta.7 => 6.5.0-beta.7
    @storybook/testing-library: ^0.0.11 => 0.0.11

### Describe the Bug

Storybook 6.5 introduces MDXv2 support as described here:

https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6

### Link to Minimal Reproducible Example

https://github.com/shilman/vite-react-mdx2

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment] 2022-05-11 15:17
Thanks for the reproduction.  I'm going to close this as a duplicate of https://github.com/storybookjs/builder-vite/issues/234.

**Closed by IanVS** 2022-05-11 15:17 UTC
Labels: bug, duplicate
